### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/qdc#1]
This Package will be removed in 7 days from KCP.

Reason: **Unmaintained**
Reason: **Broken**
`==> ERROR: Failure while downloading https://build.opensuse.org/source/KDE:Extra/qrae/qrae-0.4.2.tar.bz2`

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by forostm** [comment]
updated to latest version.
